routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes();
Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login','Auth\LoginController@login');

Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function(){
    Route::get('/', function () {
        return redirect('case');
    });
    // Route::get('/dashboard', function () {
    //     return view('dashboard');
    // });
    Route::resource('case','CaseController');
    Route::get('/query-city/{id}','CaseController@districtsCity');
    Route::get('/query-province/{id}','CaseController@districtsProvince');
    Route::get('/query-district/{id}','CaseController@commune');
    Route::get('/query-districtProvince/{id}','CaseController@communeProvince');

    Route::resource('news','NewsController');

    Route::resource('token','TokenController');
    
    Route::get('user-location/realtime','UserLocationController@showRealTimeLocations')->name('user.realtime.locations');
    Route::post('user-location/request-realtime','UserLocationController@pushResquestRealTimeLocation');

    Route::resource('user-location','UserLocationController');
    Route::post('user-location/get','UserLocationController@getUserLocation');
    Route::post('user-location/get-all','UserLocationController@getAllUserRealTimeLocation');

    
    Route::get('plot/all-cases','PlotController@allCases');

    Route::resource('city','CityController');

    Route::resource('province','ProvinceController');

    Route::resource('khan','KhanController');

    Route::resource('krong_srok','KrongSrokController');

    Route::resource('sangkat','SangkatController');
    
    Route::resource('sangkat_khum','SangkatKhumController');
    
    Route::get('plot/file/{folder_name}/{file_name}',function ($folder_name,$file_name){
        $path = storage_path() . '/app/' . $folder_name . '/'  . $file_name;
        $file = File::get($path);
        $type = File::mimeType($path);
        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);
        return $response;
    });

    Route::get('/home', function ()
    {
        return redirect('case');
    })->name('home');
});

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{

    protected $fillable = [
        'name', 'created_by', 'updated_by','created_at', 'updated_at',
    ];

    public static function getIDCity($str){
        $city = City::select('id')->where('name','=',$str)->first();
        $city_id = $city->id;
        return $city_id;
    }

    public function creator()
    {
        return $this->belongsTo('App\User','created_by');
    }

    public function updater()
    {
        return $this->belongsTo('App\User','updated_by');
    }
    
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\City;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use DB;
class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $city = City::orderBy('name')->get();
        return view('city.index',compact('city'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('city.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $v = $this->validate($request,[
            'name'=>'required|max:256',
        ]);
            
        $city = new City();
        $city->name =  $request->name;
        $city->created_by = Auth::id();
        $city->updated_by = Auth::id();
        $city->save();
        $this->alertMessage($request,1,true);
        return redirect(route('city.show',$city->id));     
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data  = City::where('id',$id)->with('creator','updater')->first();
        return view('city.show',compact('data'));
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = City::where('id',$id)->first();
        return view('city.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $v = $this->validate($request,[
            'name'=>'required'        
        ]);

        $city = City::where('id',$id)->first();
        $city->name = $request->name;
        $city->updated_by = Auth::id();

        $city->save();
        $this->alertMessage($request,2,true);
        return redirect(route('city.show',$city->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        City::where('id',$request->id)->delete();
        $this->alertMessage($request,3,true);
        return response()->json([
             'status'=>'success'
        ],200);
    }

    // public function delete(Request $request)
    // {
    //     $obj =  City::where('id',$request->id)->delete();

    //     $this->alertMessage($request,3,true);
    //     return response()->json([
    //         'status'=>'success'
    //     ],200);
    // }

}

resources/views/city/create.blade.php
@extends('layout.master')
@section('style')
@endsection
@section('content')
    <div class="container-fluid">
      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h4 mb-0 text-gray-800">Create ទីក្រុង</h1>
        <a href="{{route('city.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>
      </div>
      <div class="card shadow mb-4">
        {{-- <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Create Case</h6>
        </div> --}}
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <div class=" col-md-12">
              <form class="form-horizontal" method="POST" action="{{route('city.store')}}">
                @csrf
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text city" for="name">City</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control name" value="{{old('name')}}" id="name" placeholder="Enter City" name="name">
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                  </div>
                </div>
                <div class="form-group " style="text-align:end; padding-top:10px">  
                  <button type="submit" class="btn btn-primary btn-sm pull-right"> Save </button>
                </div>
              </form>
            </div> 
          </div>
        </div>
      </div>
    </div>
@endsection
@section('script')
@endsection

resources/views/city/edit.blade.php
@extends('layout.master')
@section('style')
@endsection
@section('content')
    <div class="container-fluid">
      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h4 mb-0 text-gray-800">Update ទីក្រុង</h1>
        <a href="{{route('city.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>
      </div>
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <div class=" col-md-12">
              <form class="form-horizontal" method="POST" action="{{route('city.update',$data->id)}}">
                @csrf
                @method('PUT')
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text" for="name">City</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" value="{{old('name') ?? $data->name}}" id="name" placeholder="Enter City" name="name">
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                  </div>
                </div>                
                <div class="form-group " style="text-align:end; padding-top:10px">
                  <button type="submit" class="btn btn-primary btn-sm pull-right"> Save </button>
                </div>
              </form>
            </div> 
          </div>
        </div>
      </div>

      </div>
      <!-- /.container-fluid -->

@endsection

@section('script')

@endsection

resources/views/city/index.blade.php
@extends('layout.master')
@section('style')
  @include('partials.css-plugin-for-table')
@endsection
@section('content')  
    <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h4 mb-0 text-gray-800">ទីក្រុង List</h1>
          <div>
            <a href="{{route('city.create')}}" class="btn btn-sm btn-primary "><i class="fas fa-add"></i> Create New</a>
          </div>
        </div>
        <div class="card shadow mb-4">
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <td >&numero;</td>
                    <th>Cities</th>
                    <th style="width:185px">Created At</th>
                    <th style="width:185px">Updated At</th>
                    <th style="text-align:center; width:100px">Actions</th>
                  </tr>
                </thead>                
                <tbody>
                @php
                      $page = 0;
                      if(Request::get('page'))
                        $page  = Request::get('page')-1;
                      
                      $index = $page*20 + 1;
                      $key = 0
                  @endphp
                  @foreach (@$city  as $key => $item)
                    
                    <tr>
                      <td>{{$key + $index}}</td>
                      <td>{{$item->name}}</td>
                      <td>{{$item->created_at}}</td>
                      <td>{{$item->updated_at}}</td>
                      <td align="center">
                        <a href="{{ route('city.edit',$item->id)}}">
                          <i class="fas fa-edit"></i>
                        </a>
                        <a href="#" data-toggle="modal" data_id="{{$item->id}}" data-target="#modal-delete" onclick="onClickDelete('city/destroy',{{$item->id}})">
                          <i class="fas fa-trash"></i>
                        </a>
                        <a href="{{ route('city.show',$item->id)}}">
                          <i class="fas fa-eye"></i>
                        </a>
                      </td>
                    </tr>
                    @php
                        $key++;
                    @endphp
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
@endsection
@section('script') 
  @include('partials.js-plugin-for-table')
@endsection

resources/views/city/show.blade.php
@extends('layout.master')
@section('style')
    <link rel="stylesheet" href="{{asset('plugins/select_country/css/countrySelect.css')}}">

@endsection
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

      <div class="d-sm-flex align-items-center justify-content-between mb-4"> 
        <h1 class="h4 mb-0 text-gray-800"> Details ទីក្រុង</h1>
        <div>
          <a href="{{route('city.edit',@$data->id)}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-add"></i> Update</a>
          <a href="{{route('city.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>

        </div>
      </div>
      <!-- DataTales Example -->
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <dl class = "dl-horizontal">
             
              <dt>City</dt>
              <dd>{{$data->name}}</dd>
              <br/><br/>
              <dt>Created By</dt>
              <dd>{{$data->creator->name}}<br></dd>
              <br/><br/>
              <dt>Updated By</dt>
              <dd>{{$data->updater->name}}<br/></dd>
              <br/><br/>
              <dt>Created At</dt>
              <dd>{{$data->created_at}}<br></dd>
              <br/><br/>
              <dt>Updated At</dt>
              <dd>{{$data->updated_at}}<br/></dd>
            </dl>
          </div>
        </div>
      </div>

      </div>
      <!-- /.container-fluid -->
@endsection

@section('script')
      
@endsection