routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes();
Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login','Auth\LoginController@login');

Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function(){
    Route::get('/', function () {
        return redirect('case');
    });
    // Route::get('/dashboard', function () {
    //     return view('dashboard');
    // });
    Route::resource('case','CaseController');
    Route::get('/query-city/{id}','CaseController@districtsCity');
    Route::get('/query-province/{id}','CaseController@districtsProvince');
    Route::get('/query-district/{id}','CaseController@commune');
    Route::get('/query-districtProvince/{id}','CaseController@communeProvince');

    Route::resource('news','NewsController');

    Route::resource('token','TokenController');
    
    Route::get('user-location/realtime','UserLocationController@showRealTimeLocations')->name('user.realtime.locations');
    Route::post('user-location/request-realtime','UserLocationController@pushResquestRealTimeLocation');

    Route::resource('user-location','UserLocationController');
    Route::post('user-location/get','UserLocationController@getUserLocation');
    Route::post('user-location/get-all','UserLocationController@getAllUserRealTimeLocation');

    
    Route::get('plot/all-cases','PlotController@allCases');

    Route::resource('city','CityController');

    Route::resource('province','ProvinceController');

    Route::resource('khan','KhanController');

    Route::resource('krong_srok','KrongSrokController');

    Route::resource('sangkat','SangkatController');
    
    Route::resource('sangkat_khum','SangkatKhumController');
    
    Route::get('plot/file/{folder_name}/{file_name}',function ($folder_name,$file_name){
        $path = storage_path() . '/app/' . $folder_name . '/'  . $file_name;
        $file = File::get($path);
        $type = File::mimeType($path);
        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);
        return $response;
    });

    Route::get('/home', function ()
    {
        return redirect('case');
    })->name('home');
});

app/SangkatKhum.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SangkatKhum extends Model
{
    protected $fillable = [
        'name', 'krong_srok_id','created_by', 'updated_by','sangkat','created_at', 'updated_at',
    ];

    public static function getIDSangkatKhum($str){
        $khan = KrongSrok::select('id')->where('name','=',$str)->first();
        $khan_id = $khan->id;
        return $khan_id;
    }

    public function creator()
    {
        return $this->belongsTo('App\User','created_by');
    }

    public function updater()
    {
        return $this->belongsTo('App\User','updated_by');
    }

    public function krongsrok()
    {
        return $this->belongsTo('App\KrongSrok','krong_srok_id','id');
    }
}

app/Http/Controllers/SangkatKhumController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\SangkatKhum;
use App\KrongSrok;
use App\Khan;
use App\Sangkat;

class SangkatKhumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sangkat_khum = SangkatKhum::orderBy('krong_srok_id')->get();
        return view('sangkat_khum.index',compact('sangkat_khum'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = KrongSrok::orderBy('name')->get(); 
        return view('sangkat_khum.create',compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $v = $this->validate($request,[
            'name'=>'required|max:256',
        ]);
        
        $sangkat = 0;
        if($request->khum != 1)
            $sangkat = 1;

        $sangkat_khum = new SangkatKhum();
        $sangkat_khum->name =  $request->name;
        $sangkat_khum->krong_srok_id =  $request->krongsrok;
        $sangkat_khum->created_by = Auth::id();
        $sangkat_khum->updated_by = Auth::id();
        $sangkat_khum->sangkat = $sangkat;
        $sangkat_khum->save();

        $this->alertMessage($request,1,true);
        return redirect(route('sangkat_khum.show',$sangkat_khum->id));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data  = SangkatKhum::where('id',$id)->with('creator','updater')->first();
        return view('sangkat_khum.show',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = SangkatKhum::where('id',$id)->first();
        $krong_srok = KrongSrok::orderBy('name')->get(); 
        return view('sangkat_khum.edit',compact('data','krong_srok'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $v = $this->validate($request,[
            'name'=>'required|max:256',
        ]);
        
        $sangkat = 0;
        if($request->khum != 1)
            $sangkat = 1;

        $sangkat_khum = SangkatKhum::where('id',$id)->first();
        $sangkat_khum->name =  $request->name;
        $sangkat_khum->krong_srok_id =  $request->krongsrok;
        $sangkat_khum->updated_by = Auth::id();
        $sangkat_khum->sangkat = $sangkat;
        $sangkat_khum->save();

        $this->alertMessage($request,1,true);
        return redirect(route('sangkat_khum.show',$sangkat_khum->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    function destroy(Request $request)
    {
        SangkatKhum::where('id',$request->id)->delete();
        $this->alertMessage($request,3,true);
        return response()->json([
             'status'=>'success'
        ],200);
    }

    // public function delete(Request $request)
    // {
    //     $obj =  SangkatKhum::where('id',$request->id)->delete();

    //     $this->alertMessage($request,3,true);
    //     return response()->json([
    //         'status'=>'success'
    //     ],200);
    // }
}

resources/views/sangkat_khum/create.blade.php
@extends('layout.master')
@section('style')
@endsection
@section('content')
    <div class="container-fluid">
      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h4 mb-0 text-gray-800">Create សង្កាត់ និង​ ឃុំ</h1>
        <a href="{{route('sangkat_khum.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>
      </div>
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <div class=" col-md-12">
              <form class="form-horizontal" method="POST" action="{{route('sangkat_khum.store')}}">
                @csrf
                <div class="form-group row">
                  <label class="control-label col-sm-2 form-label-text" for="city">Krong & Srok</label>
                  <div class="col-sm-10">
                    <select name="krongsrok" id="krongsrok" class="form-control">
                        <option class="form-control" value="0">Select District</option>
                        @foreach ($data as $info)
                        <option value="{{ $info['id'] }}">{{ $info['name'] }}</option>
                        @endforeach
                    </select>
                  </div>
                </div>
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text" for="name">Khum</label>
                  <div class="col-sm-10">
                    <input type="checkbox" value="1" name="khum" class="custom-checkbox khum"> For create khum
                    <span class="text-danger">{{ $errors->first('khum') }}</span>
                  </div>
                </div>
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text lbname" for="name">Sangkat</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control name" value="{{old('name')}}" id="name" placeholder="Enter Sangkat" name="name">
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                  </div>
                </div>
                <div class="form-group " style="text-align:end; padding-top:10px">  
                  <button type="submit" class="btn btn-primary btn-sm pull-right"> Save </button>
                </div>
              </form>
            </div> 
          </div>
        </div>
      </div>
    </div>
@endsection
@section('script')
<script>
  $(document).ready(function(){
    $(".khum").click(function(){
        if(this.checked){
          $(".lbname").text("Khum");
          $(".name").attr("placeholder","Enter Khum");
        }else{
          $(".lbname").text("Sangkat");
          $(".name").attr("placeholder","Enter Sangkat");
        }
    });
  });
</script>
@endsection

resources/views/sangkat_khum/edit.blade.php
@extends('layout.master')
@section('style')
@endsection
@section('content')
    <div class="container-fluid">
      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h4 mb-0 text-gray-800">Update សង្កាត់ និង ឃុំ</h1>
        <a href="{{route('sangkat_khum.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>
      </div>
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <div class=" col-md-12">
            <form class="form-horizontal" method="POST" action="{{route('sangkat_khum.update',$data->id)}}">
                @csrf
                @method('PUT')
                <div class="form-group row">
                  <label class="control-label col-sm-2 form-label-text" for="krongsrok">Krong & Srok</label>
                  <div class="col-sm-10">
                    <select name="krongsrok" id="krongsrok" class="form-control">
                        <option class="form-control" value="0">Select Krong & Srok</option>
                        @foreach ($krong_srok as $info)
                        <option value="{{$info['id']}}" {{ $info['id'] == $data->krong_srok_id ? 'selected' : '' }}>{{ $info['name'] }}</option>
                        @endforeach
                    </select>
                  </div>
                </div>
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text" for="name">Khum</label>
                  <div class="col-sm-10">
                    <input type="checkbox" value="1" name="khum" class="custom-checkbox khum"> For create khum
                    <span class="text-danger">{{ $errors->first('khum') }}</span>
                  </div>
                </div>
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text lbname" for="name">Sangkat</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control name" value="{{old('name') ?? $data->name }}" id="name" placeholder="Enter Sangkat" name="name">
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                  </div>
                </div>
                <div class="form-group " style="text-align:end; padding-top:10px">  
                  <button type="submit" class="btn btn-primary btn-sm pull-right"> Save </button>
                </div>
              </form>
            </div> 
          </div>
        </div>
      </div>

      </div>
      <!-- /.container-fluid -->

@endsection
@section('script')
<script>
  $(document).ready(function(){
    $(".khum").click(function(){
        if(this.checked){
          $(".lbname").text("Khum");
          $(".name").attr("placeholder","Enter Khum");
        }else{
          $(".lbname").text("Sangkat");
          $(".name").attr("placeholder","Enter Sangkat");
        }
    });
  });
</script>
@endsection

resources/views/sangkat_khum/index.blade.php
@extends('layout.master')
@section('style')
  @include('partials.css-plugin-for-table')
@endsection
@section('content')    
    <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h4 mb-0 text-gray-800"> សង្កាត់ និង​​ ឃុំ List</h1>
          <div>
            <a href="{{route('sangkat_khum.create')}}" class="btn btn-sm btn-primary "><i class="fas fa-add"></i> Create New</a>
          </div>
        </div>
        <div class="card shadow mb-4">
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <td >&numero;</td>
                    <th>Krong & Srok</th>
                    <th>Sangkat & Khum</th>
                    <th style="width:185px">Created At</th>
                    <th style="width:185px">Updated At</th>
                    <th style="text-align:center; width:100px">Actions</th>
                  </tr>
                </thead>                
                <tbody>
                  @php
                      $page1 = 0;
                      if(Request::get('page1'))
                        $page1  = Request::get('page1')-1;
                      
                      $index = $page1*20 + 1;
                  @endphp
                  @foreach (@$sangkat_khum as $key => $item)
                    <tr>
                      <td>{{$key + $index}}</td>
                      <td>{{$item->krongsrok['name'] ?? ''}}</td>
                      <td>{{$item->name}}</td>
                      <td>{{$item->created_at}}</td>
                      <td>{{$item->updated_at}}</td>
                      <td align="center">
                        <a href="{{route('sangkat_khum.edit',$item->id)}}">
                          <i class="fas fa-edit"></i>
                        </a>
                        <a href="#" data-toggle="modal" data_id="{{$item->id}}" data-target="#modal-delete" onclick="onClickDelete('sangkat_khum/destroy',{{$item->id}})">
                          <i class="fas fa-trash"></i>
                        </a>
                        <a href="{{route('sangkat_khum.show',$item->id)}}">
                          <i class="fas fa-eye"></i>
                        </a>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
@endsection
@section('script')
  @include('partials.js-plugin-for-table')
@endsection

resources/views/sangkat_khum/show.blade.php
@extends('layout.master')
@section('style')
    <link rel="stylesheet" href="{{asset('plugins/select_country/css/countrySelect.css')}}">

@endsection
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h4 mb-0 text-gray-800"> Details សង្កាត់ និង​ ឃុំ</h1>
        <div>
          <a href="{{route('sangkat_khum.edit',@$data->id)}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-add"></i> Update</a>
          <a href="{{route('sangkat_khum.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>

        </div>
      </div>
      <!-- DataTales Example -->
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <dl class = "dl-horizontal">
             
              <dt>Sangkat & Khum</dt>
              <dd>{{$data->name}}</dd>
              <br/><br/>
              <dt>Created By</dt>
              <dd>{{$data->creator->name}}<br></dd>
              <br/><br/>
              <dt>Updated By</dt>
              <dd>{{$data->updater->name}}<br/></dd>
              <br/><br/>
              <dt>Created At</dt>
              <dd>{{$data->created_at}}<br></dd>
              <br/><br/>
              <dt>Updated At</dt>
              <dd>{{$data->updated_at}}<br/></dd>
{{-- 
              <dd>
                  <span class="badge badge-primary" v-for="tag in tags">{{tag}}</span><br>
              </dd>
              <br/><br/>
              <dt>Created By</dt>
              <dd>{{created_by}}<br></dd>
              <br/><br/>
              <dt>Created At</dt>
              <dd>{{formatDate(data.created_at)}}<br></dd>
              <br/><br/>
              <dt>Updated At</dt>
              <dd>{{formatDate(data.updated_at)}}<br/></dd>
              <br/><br/>
              <dt>Attachment</dt> --}}
            </dl>
          </div>
        </div>
      </div>

      </div>
      <!-- /.container-fluid -->
@endsection

@section('script')
      
@endsection