routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes();
Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login','Auth\LoginController@login');

Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function(){
    Route::get('/', function () {
        return redirect('case');
    });
    // Route::get('/dashboard', function () {
    //     return view('dashboard');
    // });
    Route::resource('case','CaseController');
    Route::get('/query-city/{id}','CaseController@districtsCity');
    Route::get('/query-province/{id}','CaseController@districtsProvince');
    Route::get('/query-district/{id}','CaseController@commune');
    Route::get('/query-districtProvince/{id}','CaseController@communeProvince');

    Route::resource('news','NewsController');

    Route::resource('token','TokenController');
    
    Route::get('user-location/realtime','UserLocationController@showRealTimeLocations')->name('user.realtime.locations');
    Route::post('user-location/request-realtime','UserLocationController@pushResquestRealTimeLocation');

    Route::resource('user-location','UserLocationController');
    Route::post('user-location/get','UserLocationController@getUserLocation');
    Route::post('user-location/get-all','UserLocationController@getAllUserRealTimeLocation');

    
    Route::get('plot/all-cases','PlotController@allCases');

    Route::resource('city','CityController');

    Route::resource('province','ProvinceController');

    Route::resource('khan','KhanController');

    Route::resource('krong_srok','KrongSrokController');

    Route::resource('sangkat','SangkatController');
    
    Route::resource('sangkat_khum','SangkatKhumController');
    
    Route::get('plot/file/{folder_name}/{file_name}',function ($folder_name,$file_name){
        $path = storage_path() . '/app/' . $folder_name . '/'  . $file_name;
        $file = File::get($path);
        $type = File::mimeType($path);
        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);
        return $response;
    });

    Route::get('/home', function ()
    {
        return redirect('case');
    })->name('home');
});

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    //
    public function creator()
    {
        return $this->belongsTo('App\User','created_by');
    }
    public function updater()
    {
        return $this->belongsTo('App\User','updated_by');
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\News;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $datas = News::orderBy('query_number')->with('creator')->get();
        $title = 'Message List';
        return view('news.index', compact('datas','title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $title = 'Create Message';

        return view('news.create',compact('title'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // $v = $this->validate($request,[
        //     'query_number'=>'required|numeric|unique:news',
        //     'body'=>'required',
            
        // ]);
        // $obj = new News();

        // $obj->query_number = $request->query_number;
        // $obj->body = $request->body;
        // $obj->created_by = Auth::id();
        // $obj->updated_by = Auth::id();

        // $obj->save();

        // $this->alertMessage($request,1,true);

        // return redirect(route('news.show',$obj->id));

        $v = Validator::make($request->all(),[
            'query_number'=>'required|numeric|max:128|min:0|unique:news',
            'body'=>'required',
            // 'description'=>'required'
        ]);
        if($v->fails())
            return $this->apiResponseError(422,$v->errors()->all());

        $obj = new News();

        $obj->query_number = $request->query_number;
        //clear  link text
        $body = strip_tags($request->body);
        $obj->body = $body;
        $description = strip_tags($request->description);
        $obj->description = $description;

        $obj->created_by = Auth::id();
        $obj->updated_by = Auth::id();

        $obj->save();

        $this->alertMessage($request);
        return $this->apiResponseSuccess($obj);



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $data  = News::where('id',$id)->with('creator','updater')->first();
        $title = 'Message Details';

        return view('news.show',compact('data','title'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data = News::where('id',$id)->first();
        $title = 'Update Message';

        return view('news.edit',compact('data','title'));


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $v = Validator::make($request->all(),[
            'query_number'=>'required|numeric|max:128|min:0|unique:news,query_number, '.$id,
            'body'=>'required',
            // 'description'=>'required'
        ]);
        if($v->fails())
            return $this->apiResponseError(422,$v->errors()->all());

        $obj = News::where('id',$id)->first();

        $obj->query_number = $request->query_number;
        //clear  link text
        $body = strip_tags($request->body);
        $obj->body = $body;
        $description = strip_tags($request->description);
        $obj->description = $description;
        $obj->updated_by = Auth::id();

        $obj->save();

        $this->alertMessage($request,2,true);

        return $this->apiResponseSuccess($obj);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        News::where('id',$request->id)->delete();
        $this->alertMessage($request,3,true);
        return response()->json([
             'status'=>'success'
        ],200);
    }
    // public function delete(Request $request)
    // {
    //     //
        
    //     $obj =  News::where('id',$request->id)->delete();

    //     $this->alertMessage($request,3,true);
    //     return response()->json([
    //         'status'=>'success'
    //     ],200);


    // }
}

resources/views/news/create.blade.php
@extends('layout.master')
@section('style')
  @include('partials.emoji.css-for-twemoji')
  @include('partials.emoji.script-for-emoji')
  @include('partials.css-plugin-for-toastr')
  @include('partials.emoji.css-for-emoji-editor')

  
@endsection
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h5 mb-0 text-gray-800">Create Message</h1>
        <a href="{{route('news.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>
      </div>
      <!-- DataTales Example -->
      <div class="card shadow mb-4">
        {{-- <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Create Case</h6>
        </div> --}}
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <div class=" col-md-12">
              <form class="form-horizontal" method="POST" action="{{route('news.store')}}">
                @csrf

                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Query Number</label>
                  <div class="col-sm-10">
                    <input type="number" class="form-control" value="{{old('query_number')}}" id="query_number" placeholder="Enter Query Number" name="query_number">
                    <span class="text-danger">{{ $errors->first('query_number') }}</span>
                  </div>
                </div>
                {{-- <div class="form-group row">
                  <label class="control-label col-sm-2 form-label-text" for="body">Body</label>
                  <div class="col-sm-10">    
                    <textarea name="body" id="body" class="form-control"  rows="4">{{old('body')}}</textarea>
                    <span class="text-danger">{{ $errors->first('body') }}</span>    
                  </div>
                </div> --}}
                <div class="form-group row">
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="body">Body</label>
                  <div class="col-sm-10">    
                    <textarea class="form-control textarea-emoji" rows="4" name="emoji_input"  id="twemoji-picker" ></textarea>
                    <div id="emoji-pop">
                      <div class="sp-arrow"></div>
                    </div>
                    <span class="text-danger">{{ $errors->first('body') }}</span>    
                  </div>
                </div>
                
                <div class="form-group row">
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="description">Description</label>
                  <div class="col-sm-10">    
                    <textarea name="desc" id="description" class="form-control" rows="4">{{old('desc')}}</textarea>
                    <div id="emoji-pop">
                      <div class="sp-arrow"></div>
                    </div>
                    <span class="text-danger">{{ $errors->first('body') }}</span>    
                  </div>
                </div>
                
                <div class="form-group " style="text-align:end; padding-top:10px">
                    
                  <button type="button" class="btn btn-primary btn-sm pull-right" onclick="saveData()"> Save </button>
                </div>
              </form>
            </div> 
          </div>
        </div>
      </div>

      </div>
      <!-- /.container-fluid -->

@endsection

@section('script')

@include('partials.emoji.js-for-emoji')
@include('partials.js-plugin-for-toastr')

<script>


  initializeEmojiPicker();
  initializeEmojiPicker('description');

  
  function saveData(){
      var query_number = $('#query_number').val()

      var body = $('#twemoji-picker').text()
    
      body = cleanTextWithEmoji(body);
      var desc = $('#description').val();
      desc = cleanTextWithEmoji(desc);

      $.ajax({
          type: 'post',
          url : '{{route('news.store')}}',
          data:{query_number: query_number,body:body,description:desc  },

        success: function(r){

            if(r.status === 'success'){
              console.log(r.data.id)
              window.location = '/news/'+r.data.id;
            }else{
            var error = ''
              r.msg.forEach(element => {
                error += element +'\n'
              });
              toastr["error"](error)            
            }
          },
          error: function(e) {
              console.log(e);
              toastr["error"]("Creat record failed!") 


          }
      })

  }

</script>

@endsection

resources/views/news/edit.blade.php
@extends('layout.master')
@section('style')
  @include('partials.css-plugin-for-toastr')
  @include('partials.emoji.css-for-twemoji')
  @include('partials.emoji.script-for-emoji')
  @include('partials.emoji.css-for-emoji-editor')

@endsection
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h5 mb-0 text-gray-800">Update Message</h1>
        <a href="{{route('news.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>
      </div>
      <!-- DataTales Example -->
      <div class="card shadow mb-4">
        {{-- <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Create Case</h6>
        </div> --}}
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <div class=" col-md-12">
              <form class="form-horizontal" method="POST" action="{{route('news.update',$data->id)}}">
                @csrf

                @method('PUT')
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Query Number</label>
                  <div class="col-sm-10">
                    <input type="number" class="form-control" value="{{old('query_number')??$data->query_number}}" id="query_number" placeholder="Enter Query Number" name="query_number">
                    <span class="text-danger">{{ $errors->first('query_number') }}</span>
                  </div>
                </div>
                {{-- <div class="form-group row">
                  <label class="control-label col-sm-2 form-label-text" for="body">Body</label>
                  <div class="col-sm-10">    
                    <textarea name="body" id="body" class="form-control"  rows="4">{{old('body')??$data->body}}</textarea>
                    <span class="text-danger">{{ $errors->first('body') }}</span>    
                  </div>
                </div> --}}
                <div class="form-group row">
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="body">Body</label>
                  <div class="col-sm-10">    
                    <textarea class="form-control textarea-emoji" rows="4" name="emoji_input"  id="twemoji-picker" >{!! $data->body !!}</textarea>
                    <div id="emoji-pop">
                      <div class="sp-arrow"></div>
                    </div>
                    <span class="text-danger">{{ $errors->first('body') }}</span>    
                  </div>
                </div>
                
                <div class="form-group row">
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="description">Description</label>
                  <div class="col-sm-10">    
                    <textarea name="description" id="description" class="form-control" rows="4">{!! $data->description !!}</textarea>
                    <span class="text-danger">{{ $errors->first('description') }}</span>    
                  </div>
                </div>
                <div class="form-group " style="text-align:end; padding-top:10px">
                    
                  <button type="button" class="btn btn-primary btn-sm pull-right" onclick="saveData()"> Save </button>
                </div>
              </form>
            </div> 
          </div>
        </div>
      </div>

      </div>
      <!-- /.container-fluid -->

@endsection

@section('script')

    @include('partials.emoji.js-for-emoji')
    @include('partials.js-plugin-for-toastr')

    <script>
      var body_textarea = $('#twemoji-picker')
      var description_textarea = $('#description')

      initializeEmojiPicker();

      initializeEmojiPicker('description');

      var emoji_body_input_content  = $(body_textarea).parents().find('div.twemoji-textarea')[0];
      $(emoji_body_input_content).html(twemoji.parse(body_textarea.text()))

      var description_input_content  = $(description_textarea).parents().find('div.twemoji-textarea')[1];
      $(description_input_content).html(twemoji.parse(description_textarea.text()))
      
      function saveData(){
          var query_number = $('#query_number').val()
          var body = $('#twemoji-picker').val()
          body = cleanTextWithEmoji(body);
          var description = $('#description').val()
          description = cleanTextWithEmoji(description);

          $.ajax({
            type: 'put',
            url : '{{route("news.update",$data->id)}}',
            data:{query_number: query_number,body:body,description:description  },

            success: function(r){

                if(r.status === 'success'){
                  console.log(r.data.id)
                  window.location = '/news/'+r.data.id;
                }else{
                  var error = ''
                  r.msg.forEach(element => {
                    error += element +'\n'
                  });
                  toastr["error"](error)            
                }
            },
            error: function(e) {
                console.log(e);
                toastr["error"]("Creat update failed!") 


            }
        })

      }
    </script>

@endsection

resources/views/news/index.blade.php
@extends('layout.master')
@section('style')
  @include('partials.css-plugin-for-table')

@endsection
@section('content')
    <!-- Begin Page Content -->
    
    <div class="container-fluid">
        
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h5 mb-0 text-gray-800">Message List</h1>
          <div >

            <a href="{{route('news.create')}}" class="btn btn-sm btn-primary "><i class="fas fa-add"></i> Create New</a>

          </div>
        </div>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th >&numero;</th>
                    <th style="text-align:center; width:100px">Query Number</th>
                    <th>Body</th>
                    <th>Description</th>

                    <th style="width:90px">Created By</th>
                    <th style="width:90px">Created At</th>

                    <th style="text-align:center; width:100px">Actions</th>

                  </tr>
                </thead>
                
                <tbody>
                  @php
                      $page = 0;
                      if(Request::get('page'))
                        $page  = Request::get('page')-1;
                      
                      $index = $page*20 + 1;
                  @endphp
                  @foreach (@$datas as $key => $item)
                    <tr>
                      <td>{{$key + $index}}</td>
                      <td align="center">{{$item->query_number}}</td>
                      <td style="word-break:break-all; white-space: pre-wrap; ">{!! nl2br($item->body) !!}</td>
                      <td style="word-break:break-all; white-space: pre-wrap;">{!! nl2br($item->description) !!}</td>

                      <td>{{@$item->creator->name??'N/A'}}</td>
                      <td>{{$item->created_at}}</td>

                      <td align="center">
                        <a href="{{route('news.edit',$item->id)}}">
                          <i class="fas fa-edit"></i>
                        </a>
                        <a href="#" data-toggle="modal" data_id="{{$item->id}}" data-target="#modal-delete" onclick="onClickDelete('news/destroy',{{$item->id}})">
                          <i class="fas fa-trash"></i>
                        </a>
                        <a href="{{route('news.show',$item->id)}}">
                          <i class="fas fa-eye"></i>
                        </a>
                      </td>

                    </tr>
                  @endforeach
                  
                </tbody>
              </table>
            </div>
            {{-- {{@$datas->appends(request()->except('page'))->links()}} --}}
          </div>
        </div>

    </div>
      <!-- /.container-fluid -->
@endsection

@section('script')
    @include('partials.js-plugin-for-table')
@endsection

resources/views/news/show.blade.php
@extends('layout.master')
@section('style')
    <link rel="stylesheet" href="{{asset('plugins/select_country/css/countrySelect.css')}}">
    @include('partials.emoji.script-for-emoji')
    @include('partials.emoji.css-for-twemoji')

@endsection
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h5 mb-0 text-gray-800"> Message Details </h1>
        <div>
          <a href="{{route('news.edit',@$data->id)}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-add"></i> Update</a>
          <a href="{{route('news.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>

        </div>
      </div>
      <!-- DataTales Example -->
      <div class="card shadow mb-4">
        {{-- <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Create Case</h6>
        </div> --}}
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Query Number</b></label>
              <div class="col-sm-10">
                <p>{{$data->query_number}}</p>
              </div>
            </div>
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Body</b></label>
              <div class="col-sm-10">
                <p id="body" style="white-space: pre-wrap; line-height: 1.3" >{!! nl2br($data->body) !!}</p>
              </div>
            </div>
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Description</b></label>
              <div class="col-sm-10">
                <p id="description" style="white-space: pre-wrap; line-height: 1;" >{!! nl2br($data->description) !!}</p>
              </div>
            </div>
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Created By</b></label>
              <div class="col-sm-10">
                <p>{{@$data->creator->name??'N/A'}}</p>
              </div>
            </div>
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Updated By</b></label>
              <div class="col-sm-10">
                <p>{{@$data->updater->name??'N/A'}}</p>
              </div>
            </div>
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Created At</b></label>
              <div class="col-sm-10">
                <p>{{$data->created_at}}</p>
              </div>
            </div>
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Updated At</b></label>
              <div class="col-sm-10">
                <p  >{{$data->updated_at}}</p>
              </div>
            </div>
            
            {{-- <dl class = "dl-horizontal">
             
              <dt>Query Number</dt>
              <dd>{{$data->query_number}}</dd>
              <br/><br/>
              <dt>Body</dt>
              <dd id="body" style="white-space: pre-wrap; line-height: 0.5;" >{!! nl2br($data->body) !!}<br></dd>
              <br/><br/>
              <dt>Description</dt>
              <dd style="white-space: pre-wrap; line-height: 1;">{!! nl2br($data->description) !!}<br></dd>
              <br/><br/>
              <dt>Created By</dt>
              <dd>{{@$data->creator->name??'N/A'}}<br></dd>
              
              <br/><br/>
              <dt>Updated By</dt>
              <dd>{{$data->updater->name}}<br/></dd>
              <br/><br/>
              <dt>Created At</dt>
              <dd>{{$data->created_at}}<br></dd>
              <br/><br/>
              <dt>Updated At</dt>
              <dd>{{$data->updated_at}}<br/></dd>

            </dl> --}}
          </div>
        </div>
      </div>

      </div>
      <!-- /.container-fluid -->

@endsection

@section('script')
      <script>
        var body = $('#body')
        $(body).html(twemoji.parse($(body).html()))
        var description = $('#description')
        $(description).html(twemoji.parse($(description).html()))
      </script>
      
@endsection